# Generated by Django 2.1.1 on 2018-09-08 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tokenizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='redirect_count',
            field=models.IntegerField(default=0, verbose_name='Количество переходов по ссылке'),
        ),
        migrations.AlterField(
            model_name='url',
            name='token',
            field=models.CharField(help_text='Сокращенная ссылка', max_length=8, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='url',
            unique_together={('user', 'url')},
        ),
    ]
